FROM node:12.19.0 AS BUILD

WORKDIR /app
COPY . ./
ENV REACT_APP_API_TERMINAL=https://deepskills.ru
ENV REACT_APP_API_COURSE=https://dev.deepskills.ru
#ENV REACT_APP_SEO_YM_ID=88095091
RUN npm  install --force
RUN npm i --save-dev @types/redux-logger
RUN npm run build 

FROM nginx:latest
WORKDIR /var/www
COPY ./https.conf /etc/nginx/conf.d/default.conf
COPY --from=BUILD /app/build /var/www
