FROM node:12.19.0 AS BUILD

WORKDIR /app
COPY . ./
ENV REACT_APP_API_TERMINAL=https://deepskills.ru
ENV REACT_APP_API_COURSE=http://dev.deepskills.ru:3000
#ENV REACT_APP_SEO_YM_ID=88095091
RUN npm  install
RUN npm run build 

FROM nginx:latest
WORKDIR /var/www
COPY ./https.conf /etc/nginx/conf.d/default.conf
COPY --from=BUILD /app/build /var/www