export const temp = {
  description: 'Python - это язык программирования общего назначения, который становится все более популярным в науке о данных. Компании по всему миру используют Python для сбора информации из своих данных и получения конкурентного преимущества. В отличие от других руководств по Python, этот курс посвящен Python специально для науки о данных. В нашем курсе «Введение в Python» вы узнаете о эффективных способах хранения и обработки данных, а также о полезных инструментах для анализа данных, чтобы начать свой собственный анализ. Начните онлайн-курс обучения Python в DataCamp прямо сейчас.',
  parts: [
    {
      title: 'Основы Python',
      description:
        'Введение в основные концепции Python. Узнайте, как использовать Python в интерактивном режиме и с помощью сценария. Создайте свои первые переменные и познакомьтесь с основными типами данных Python.',
      isFree: true,
      status: 'untouched',
      course_id: 'python-for-beginners',
      exercises: [
        {
          title: 'Интерфейс Python',
          type: 'normal_exercise',
          exercise_id: 1,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Когда использовать Python?',
          type: 'normal_exercise',
          exercise_id: 2,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Комментарии?',
          type: 'video',
          exercise_id: 8,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Python как калькулятор',
          type: 'normal_exercise',
          exercise_id: 49,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Переменные и типы',
          type: 'normal_exercise',
          exercise_id: 49,
          xp: 50,
          status: 'untouched',
        },
      ],
    },
    {
      title: 'Списки Python',
      description:
        'Научитесь хранить, получать доступ и управлять данными в списках: первый шаг к эффективной работе с огромными объемами данных.',
      isFree: true,
      status: 'untouched',
      course_id: 'data-types-for-data-science-in-python',
      exercises: [
        {
          title: 'Интерфейс Python',
          type: 'normal_exercise',
          exercise_id: 1,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Когда использовать Python?',
          type: 'normal_exercise',
          exercise_id: 2,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Комментарии?',
          type: 'video',
          exercise_id: 8,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Python как калькулятор',
          type: 'normal_exercise',
          exercise_id: 49,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Переменные и типы',
          type: 'normal_exercise',
          exercise_id: 49,
          xp: 50,
          status: 'untouched',
        },
      ],
    },
    {
      title: 'Функции и пакеты',
      description:
        'Вы узнаете, как использовать функции, методы и пакеты для эффективного использования кода, написанного блестящими разработчиками Python. Цель состоит в том, чтобы уменьшить количество кода, необходимого для решения сложных задач!',
      isFree: false,
      status: 'untouched',
      course_id: 'introduction-to-data-science-in-python',
      exercises: [
        {
          title: 'Интерфейс Python',
          type: 'normal_exercise',
          exercise_id: 1,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Когда использовать Python?',
          type: 'normal_exercise',
          exercise_id: 2,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Комментарии?',
          type: 'video',
          exercise_id: 8,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Python как калькулятор',
          type: 'normal_exercise',
          exercise_id: 49,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Переменные и типы',
          type: 'normal_exercise',
          exercise_id: 49,
          xp: 50,
          status: 'untouched',
        },
      ],
    },
    {
      title: 'NumPy',
      description:
        'NumPy - это фундаментальный пакет Python для эффективной практики обработки данных. Научитесь работать с мощными инструментами в массиве NumPy и начните исследование данных.',
      isFree: false,
      status: 'untouched',
      course_id: 'introduction-to-data-science-in-python2',
      exercises: [
        {
          title: 'Интерфейс Python',
          type: 'normal_exercise',
          exercise_id: 1,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Когда использовать Python?',
          type: 'normal_exercise',
          exercise_id: 2,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Комментарии?',
          type: 'video',
          exercise_id: 8,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Python как калькулятор',
          type: 'normal_exercise',
          exercise_id: 49,
          xp: 50,
          status: 'untouched',
        },
        {
          title: 'Переменные и типы',
          type: 'normal_exercise',
          exercise_id: 49,
          xp: 50,
          status: 'untouched',
        },
      ],
    },
  ],
};
